### ISSUE TITLE
Append Moti chris_culvert_id to PSCIS spreadsheet comments

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2023_reporting#23]
May as well tie it together.
Be sure to distinguish between the major structures by appending column name at same time 
(ex. chris_culvert_id: 122342 or chris_hwy_structure_road_id = 2434).

Looks like all the `chris_culvert_id` are high (greater than 1,000,000 and `chris_hwy_structure_road_id` are less than 10,000 to inform `left_join` `case_when` (can query db with `select max(chris_hwy_structure_road_id) and select min from `whse_whatever.chris_hwy_structure_road_id` to confirm though)

**Comment by Mateo9569** [comment]
What happens if there is more than one moti culvert? If there is more than one pipe at a crossing we only use one modelled id, whereas they have a point for each pipe. Is it ok to just have one moti id in the pscis spreadsheet comments field? Even if there is more than one pipe. But in our reporting we can reference all moti chris culvert ids that are present in our site memos.

I QAd the moti culvert fields in Q. There was one or two that were incorrect or missing an id. And there were two crossings (modelled id 3701558 and 3700010) that were actually highway structures so I changed the `chris_culvert_id` to a `chris_hwy_structure_road_id`

**Comment by NewGraphEnvironment** [comment]
If there are more than one it could go in another mutated column and added to the comments programmatically. We can make a note to add another colum to the form in dff too…


min the comments it should be easy for the reader to understand what a chris_culvert_id refers to so it could say something more like “Ministry of Transportation chris_culvert_id: 12345”

**Comment by Mateo9569** [comment]
There is actually only two crossings in peace that might have more than one moti culvert. 

- modelled crossing 3700007 : there are two pipes right next to each other seen in assessment, but in Q there are two moti culverts that are far apart so not sure if it's the same one
![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/assets/99455166/05bd3575-d27c-44b9-b0df-a4c4b364fbac)

- modelled crossing 3702044 : only one culvert found during assessment but apparently there is supposed to be 2
![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/assets/99455166/41b8aea5-32ff-4ffc-a99d-ccbd1e9847d9)

I'm just going to leave it as is. But I will update the comments so it says "Ministry of Transportation".

**Comment by NewGraphEnvironment** [comment]
This is also the place we can document sql queries and results to confirm min and max values for these 2 parameters in province wide datasets
